/*
 * Generated by JasperReports - 2021/09/14, 10:18
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class Blank_A4_1631607511131_535114 extends JREvaluator
{


    /**
     *
     */
    private JRFillField field_Total_Amount = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_Total_Amount = (JRFillField)fm.get("Total_Amount");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 13 : 
            {
                value = "R "+((java.lang.Integer)field_Total_Amount.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 15 : 
            {
                value = new SimpleDateFormat("dd-MM-yyy").format(new Date()); //$JR_EXPR_ID=15$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 13 : 
            {
                value = "R "+((java.lang.Integer)field_Total_Amount.getOldValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 15 : 
            {
                value = new SimpleDateFormat("dd-MM-yyy").format(new Date()); //$JR_EXPR_ID=15$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 13 : 
            {
                value = "R "+((java.lang.Integer)field_Total_Amount.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 15 : 
            {
                value = new SimpleDateFormat("dd-MM-yyy").format(new Date()); //$JR_EXPR_ID=15$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
